version: '3'

services:
  client:
    build:
      context: ./client  # Path to your React app directory
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Map container port 80 to host port 3000 for development
    depends_on:
      - server

  server:
    build:
      context: ./server  # Path to your Node.js server directory
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map container port 5000 to host port 5000
